# -*- coding: utf-8 -*-
"""imc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104UGw7XuS51zx1crZNDk7S6t3Ww9GteB

# Actividad 1 - IMC
El IMC, conocido también como el Índice de masa corporal, es una medida que asocia el
peso de una persona con su talla (su altura). Este valor es utilizado normalmente como un
indicador nutricional y constituye un índice fácil y sencillo de calcular para determinar el
estado de obesidad y sobrepeso de una persona. El IMC se calcula de la siguiente manera:
𝐼𝑀𝐶 =
𝑊
𝐻
2

W : corresponde al peso de la persona en Kg.

H: corresponde a la altura en metros.

IMC: EL valor del IMC, en [Kg/m2]

Para ello, la Organización Mundial de la Salud (OMS) ha determinado una clasificación así
para distintos rangos de valores.

IMC Clasificación OMS

< 18.5 Bajo Peso

[ 18.5, 25 [ Adecuado

[ 25, 30 [ Sobrepeso

[ 30, 35[ Obesidad Grado I

[ 35, 40 [ Obesidad Grado II

> 40 Obesidad Grado III

En busca de mejorar la salud nutricional de los pacientes, se le solicita a usted como
programador el hecho de diseñar una herramienta que permita determinar el estado
nutricional de una persona.

Se solicita crear el programa imc.py que permita calcular el IMC de una persona.
1. Al programa se debe ingresar el peso en Kg y la talla (altura) en centímetros.
(1 Puntos)
2. Calcular el IMC ajustando los valores de entrada a las unidades requeridas por la
fórmula. El resultado se debe informar con 2 decimales.
(2 Puntos)
3. Entregar al usuario una salida acorde que permita conocer el valor de su IMC
además de la clasificación dada por la OMS.
"""

import math

# Entrada de datos
peso = float(input("Ingrese su peso en kg: "))
altura_cm = float(input("Ingrese su altura en cm: "))


# Calcular IMC
altura_m = altura_cm / 100  # Convertir la altura de cm a m
imc = peso / math.pow(altura_m, 2)  # Calcular el IMC

# Clasificación del IMC
if imc < 18.5:
        clasif= "Bajo Peso"
elif 18.5 <= imc < 25:
        clasif=  "Adecuado"
elif 25 <= imc < 30:
        clasif=  "Sobrepeso"
elif 30 <= imc < 35:
        clasif=  "Obesidad Grado I"
elif 35 <= imc < 40:
        clasif=  "Obesidad Grado II"
else:
        clasif=  "Obesidad Grado III"


# Salida de datos
print(f"Su IMC es: {imc:.2f} kg/m²")
print(f"La clasificación OMS es: {clasif}")

